### ISSUE TITLE
Single delete Request to delete multiple resources

### ISSUE THREAD

**Issue by razuro** [colindecarlo/uhura#4]
Thanks for a good wrapper! Just wondering how to do the above?

**Comment by colindecarlo** [comment]
I think the way that you would accomplish something like this would be to delete a set of resources associated to another resource. JSON:API talks about it [here](https://jsonapi.org/format/#crud-updating-to-many-relationships). So, I guess it all depends on how you've implemented your API.

You might be able to do it like this 

```php
$uhura->blogs(42)->comments->delete();
```

The JSON:API says that `DELETE`s **may** have bodies, at the moment, I'm not sure if Uhura can do that.

Also, sorry for the late reply, I had no idea anyone used this
